version: "3"

services:
  app:
    build: ./app
    container_name: my-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network: 
    driver: bridge
